language: node_js
node_js:
 - 8

cache:
  directories:
    - node_modules
    - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh

script:
  - ~/.meteor/meteor npm run-script coverage.lcov

after_success:
  - cat .coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
