language: node_js
node_js:
 - 8

cache:
  directories:
    - node_modules
    - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh

script:
  - ~/.meteor/meteor test --once  --driver-package meteortesting:mocha
