'use strict'

import canonical from './canonical.coffee'

export mechanics = {}

export class Mechanic
  constructor: (@name) ->
    @canon = canonical @name
    mechanics[@canon] = @
    Object.freeze @

new Mechanic 'audiophile'
new Mechanic 'backsolvers'
new Mechanic 'biology'
new Mechanic 'board games'
new Mechanic 'chemistry'
new Mechanic 'chinese'
new Mechanic 'ciphers'
new Mechanic 'classics'
new Mechanic 'code monkey'
new Mechanic 'crossword clues'
new Mechanic 'cryptic command'
new Mechanic 'duck conundrum'
new Mechanic 'ecce romani'
new Mechanic 'extraction'
new Mechanic 'finance'
new Mechanic 'Flour Bakery and Cafe'
new Mechanic 'food/cooking'
new Mechanic 'geography'
new Mechanic 'grunt work'
new Mechanic 'history/law/politics'
new Mechanic 'ID tasks'
new Mechanic 'image editing'
new Mechanic 'IPA (phonetics)'
new Mechanic 'knitting'
new Mechanic 'lgbt'
new Mechanic 'literature'
new Mechanic 'location-based'
new Mechanic 'logic puzzle'
new Mechanic 'luge'
new Mechanic 'math'
new Mechanic 'medicine'
new Mechanic 'memes'
new Mechanic 'meta squad'
new Mechanic 'minipuzzles'
new Mechanic 'MIT knowledge'
new Mechanic 'music ID'
new Mechanic 'music theory'
new Mechanic 'musicals/theater'
new Mechanic 'niche topics'
new Mechanic 'NPL flats'
new Mechanic 'origami'
new Mechanic 'panda-monium'
new Mechanic 'physical'
new Mechanic 'physics'
new Mechanic 'poetry'
new Mechanic 'pop culture'
new Mechanic 'potent potables'
new Mechanic 'puns'
new Mechanic 'runaround'
new Mechanic 'scavenger hunt'
new Mechanic 'spanish'
new Mechanic 'sports'
new Mechanic 'steganosaurus'
new Mechanic 'story interactions'
new Mechanic 'teamwork time'
new Mechanic 'text adventure'
new Mechanic 'TV and movies'
new Mechanic 'video games'
new Mechanic 'weeb'

Object.freeze mechanics

export IsMechanic = Match.Where (x) -> mechanics[x]?
